services:
  audiobookshelf:
    image: ghcr.io/advplyr/audiobookshelf:2.35.1
    # ports:
    #   - 13378:80
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - audiobooks:/audiobooks
      - blinkist:/blinkist
      - podcast:/podcast
      # The metadata directory can be stored anywhere on your computer
      # you are running ABS on
      - /home/nexus/docker-resources/audiobookshelf/metadata:/metadata
      # The config directory needs to be on the same physical machine
      # you are running ABS on
      - /home/nexus/local/audiobookshelf/config:/config
    networks:
      - proxy
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.hostname == swarm-02
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      labels:
      #TRAEFIK
        - "traefik.enable=true"
        - "traefik.http.routers.audiobooks.entrypoints=http"
        - "traefik.http.routers.audiobooks.rule=Host(`audiobooks.${DOMAIN}`)"
        - "traefik.http.middlewares.audiobooks-https-redirect.redirectscheme.scheme=https"
        - "traefik.http.routers.audiobooks.middlewares=audiobooks-https-redirect"
        - "traefik.http.routers.audiobooks-secure.entrypoints=https"
        - "traefik.http.routers.audiobooks-secure.rule=Host(`audiobooks.${DOMAIN}`)"
        - "traefik.http.routers.audiobooks-secure.tls=true"
        - "traefik.http.routers.audiobooks-secure.service=audiobooks"
        - "traefik.http.services.audiobooks.loadbalancer.server.port=80"
        - "traefik.swarm.network=proxy"
      #HOMEPAGE
        - "homepage.group=Media"
        - "homepage.name=audiobookshelf"
        - "homepage.icon=audiobookshelf.png"
        - "homepage.href=https://audiobooks.${DOMAIN}"

volumes:
  audiobooks:
    driver: local
    driver_opts:
      type: nfs
      o: addr=truenas.localdomain,nfsvers=4,rw,hard,noatime
      device: ":/mnt/ssdp1/media/audio/audiobooks"
  blinkist:
    driver: local
    driver_opts:
      type: nfs
      o: addr=truenas.localdomain,nfsvers=4,rw,hard,noatime
      device: ":/mnt/ssdp1/media/audio/blinkist"
  podcast:
    driver: local
    driver_opts:
      type: nfs
      o: addr=truenas.localdomain,nfsvers=4,rw,hard,noatime
      device: ":/mnt/ssdp1/media/audio/podcast"

networks:
  proxy:
    external: true